/**:
  ros__parameters:
    angular_velocity_offset_x: 0.0        # [rad/s]
    angular_velocity_offset_y: 0.0        # [rad/s]
    angular_velocity_offset_z: -0.019850  # [rad/s] 最新測定値（3回の平均）
    angular_velocity_stddev_xx: 0.03      # [rad/s]
    angular_velocity_stddev_yy: 0.03      # [rad/s]
    angular_velocity_stddev_zz: 0.5       # [rad/s] Yaw Rateの信頼度を低く
    acceleration_stddev: 10000.0          # [m/s^2] 加速度の信頼度を低く
